algoritmo "CONVERSOS FARENHIT PARA CELSIUS"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

f, c : real

inicio

escreva("Digite a temperatura em Fahrenheit: ")
leia(f)

c <- (f - 32) * 5 / 9

escreva("A temperatura em Celsius é: ", c)

fimalgoritmo