algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

numero: inteiro

inicio

 Escreva("Digite um número inteiro:")
    Leia(numero)

    Se numero % 2 = 0 então
        Escreva("O número é par.")
    Senão
        Escreva("O número é ímpar.")
    FimSe

fimalgoritmo